### ISSUE TITLE
tmax() default value choice

### ISSUE THREAD

**Issue by ArnaudKunzi** [CTU-Bern/btable#15]
Question about RMST.ado: 
Is there a methodological reason or other reason that I am missing to use a truncation time default as the last observed _event_ time rather than the smallest last observed _event OR follow-up_ time (so-called minimax event time)?  

Use case example: I censor a dataset (e.g. 365 days), but then am surprised that without mentioning `tmax()`, the truncation time would be set to the last event, for example 352 days. Someone calling `RMST` in a loop and not careful in setting `tmax()` might not collect the intended estimates.

**Comment by lbueti** [comment]
I would generally recommend to always use a predefined truncation time.
If the last event OR censor time is used as truncation time, the RMST estimate depends on the last censor time (if it is later than the last event time), which might be rather arbitrary. It has been suggested by e.g. Royston and Parmar to restrict tmax to "the largest uncensored time to event in the data, to avoid extrapolation of RMST estimates from a flexible parametric model" (https://doi.org/10.1186/1471-2288-13-152).
This is of course not an issue if you censor at 365 days by design (as in your example) but in this case you should just give tmax.
